spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/moneytracker
    username: moneytracker
    password: moneytracker
    driver-class-name: org.postgresql.Driver
  resources:
    static-locations: classpath:/pages/
  mvc:
    view:
      suffix: .jsp
  data:
    elasticsearch:
      cluster-nodes: localhost:9300
