spring:
  datasource:
    url: jdbc:postgresql://192.168.99.100:31010/money-tracker
    username: moneytracker
    password: moneytracker
    driver-class-name: org.postgresql.Driver
  resources:
    static-locations: classpath:/pages/
  mvc:
    view:
      suffix: .jsp
  data:
    elasticsearch:
      cluster-nodes: 192.168.99.100:31003
