DROP TABLE IF EXISTS MT_TB_USERS CASCADE;
DROP TABLE IF EXISTS MT_TB_TAGS CASCADE;
DROP TABLE IF EXISTS MT_TB_FILTER_OPTIONS CASCADE;
DROP TABLE IF EXISTS MT_TB_FILTERS CASCADE;
DROP TABLE IF EXISTS MT_TB_FILTER_TAGS CASCADE;
DROP TABLE IF EXISTS MT_TB_RULES CASCADE;
DROP TABLE IF EXISTS MT_TB_RULE_TAGS CASCADE;
DROP TABLE IF EXISTS MT_TB_REPORT_CHARTS CASCADE;
DROP TABLE IF EXISTS MT_TB_REPORTS CASCADE;

DROP SEQUENCE IF EXISTS MT_SEQ_USERS;
DROP SEQUENCE IF EXISTS MT_SEQ_TAGS;
DROP SEQUENCE IF EXISTS MT_SEQ_FILTERS;
DROP SEQUENCE IF EXISTS MT_SEQ_RULES;
DROP SEQUENCE IF EXISTS MT_SEQ_REPORTS;
