CREATE SEQUENCE IF NOT EXISTS MT_SEQ_USERS
    START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS MT_SEQ_TAGS
    START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS MT_SEQ_FILTERS
    START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS MT_SEQ_RULES
    START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS MT_SEQ_REPORTS
    START WITH 1 INCREMENT BY 1;


CREATE TABLE IF NOT EXISTS MT_TB_USERS (
    ID BIGINT DEFAULT NEXTVAL('MT_SEQ_USERS') NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT NOW() NOT NULL,
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(60) NOT NULL
);
ALTER TABLE MT_TB_USERS ADD CONSTRAINT MT_PK_USERS PRIMARY KEY(ID);


CREATE TABLE IF NOT EXISTS MT_TB_TAGS (
    ID BIGINT DEFAULT NEXTVAL('MT_SEQ_TAGS') NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT NOW() NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    COLOR VARCHAR(7) NOT NULL,
    OWNER_ID BIGINT NOT NULL
);
ALTER TABLE MT_TB_TAGS ADD CONSTRAINT MT_PK_TAGS PRIMARY KEY(ID);
ALTER TABLE MT_TB_TAGS ADD CONSTRAINT MT_FK_TAGS_OWNER_ID FOREIGN KEY(OWNER_ID) REFERENCES MT_TB_USERS(ID);


CREATE TABLE IF NOT EXISTS MT_TB_FILTERS (
    ID BIGINT DEFAULT NEXTVAL('MT_SEQ_FILTERS') NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT NOW() NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    FROM_DATE DATE,
    TO_DATE DATE,
    DESCRIPTION VARCHAR(200),
    AMOUNT_FROM DECIMAL(19, 2),
    AMOUNT_TO DECIMAL(19, 2),
    ACCOUNT_HOLDER VARCHAR(50),
    ACCOUNT VARCHAR(50),
    OFFSET_ACCOUNT VARCHAR(50),
    OWNER_ID BIGINT NOT NULL
);
ALTER TABLE MT_TB_FILTERS ADD CONSTRAINT MT_PK_FILTERS PRIMARY KEY(ID);
ALTER TABLE MT_TB_FILTERS ADD CONSTRAINT MT_FK_FILTERS_OWNER_ID FOREIGN KEY(OWNER_ID) REFERENCES MT_TB_USERS(ID);


CREATE TABLE IF NOT EXISTS MT_TB_FILTER_TAGS (
    FILTER_ID BIGINT NOT NULL,
    TAG_ID BIGINT NOT NULL
);
ALTER TABLE MT_TB_FILTER_TAGS ADD CONSTRAINT MT_PK_FILTER_TAGS PRIMARY KEY(FILTER_ID, TAG_ID);
ALTER TABLE MT_TB_FILTER_TAGS ADD CONSTRAINT MT_FK_FILTER_TAGS_FILTER_ID FOREIGN KEY(FILTER_ID) REFERENCES MT_TB_FILTERS(ID);
ALTER TABLE MT_TB_FILTER_TAGS ADD CONSTRAINT MT_FK_FILTER_TAGS_TAG_ID FOREIGN KEY(TAG_ID) REFERENCES MT_TB_TAGS(ID);


CREATE TABLE IF NOT EXISTS MT_TB_FILTER_OPTIONS (
    FILTER_ID BIGINT NOT NULL,
    NAME VARCHAR(100) NOT NULL
);
ALTER TABLE MT_TB_FILTER_OPTIONS ADD CONSTRAINT MT_FK_FILTER_OPTIONS_FILTER_ID FOREIGN KEY(FILTER_ID) REFERENCES MT_TB_FILTERS(ID);


CREATE TABLE IF NOT EXISTS MT_TB_RULES (
    ID BIGINT DEFAULT NEXTVAL('MT_SEQ_RULES') NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT NOW() NOT NULL,
    ARCHIVE BOOLEAN NOT NULL DEFAULT FALSE,
    ENABLED BOOLEAN NOT NULL DEFAULT TRUE,
    FILTER_ID BIGINT NOT NULL,
    OWNER_ID BIGINT NOT NULL
);
ALTER TABLE MT_TB_RULES ADD CONSTRAINT MT_PK_RULES PRIMARY KEY(ID);
ALTER TABLE MT_TB_RULES ADD CONSTRAINT MT_FK_RULES_FILTER_ID FOREIGN KEY(FILTER_ID) REFERENCES MT_TB_FILTERS(ID);
ALTER TABLE MT_TB_RULES ADD CONSTRAINT MT_FK_RULES_OWNER_ID FOREIGN KEY(OWNER_ID) REFERENCES MT_TB_USERS(ID);


CREATE TABLE IF NOT EXISTS MT_TB_RULE_TAGS (
    RULE_ID BIGINT NOT NULL,
    TAG_ID BIGINT NOT NULL
);
ALTER TABLE MT_TB_RULE_TAGS ADD CONSTRAINT MT_PK_RULE_TAGS PRIMARY KEY(RULE_ID, TAG_ID);
ALTER TABLE MT_TB_RULE_TAGS ADD CONSTRAINT MT_FK_RULE_TAGS_RULE_ID FOREIGN KEY(RULE_ID) REFERENCES MT_TB_RULES(ID);
ALTER TABLE MT_TB_RULE_TAGS ADD CONSTRAINT MT_FK_RULE_TAGS_TAG_ID FOREIGN KEY(TAG_ID) REFERENCES MT_TB_TAGS(ID);


CREATE TABLE IF NOT EXISTS MT_TB_REPORTS (
    ID BIGINT DEFAULT NEXTVAL('MT_SEQ_REPORTS') NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT NOW() NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    ICON VARCHAR(100) NULL,
    FILTER_ID BIGINT NOT NULL,
    OWNER_ID BIGINT NOT NULL
);
ALTER TABLE MT_TB_REPORTS ADD CONSTRAINT MT_PK_REPORTS PRIMARY KEY(ID);
ALTER TABLE MT_TB_REPORTS ADD CONSTRAINT MT_FK_REPORTS_FILTER_ID FOREIGN KEY(FILTER_ID) REFERENCES MT_TB_FILTERS(ID);
ALTER TABLE MT_TB_REPORTS ADD CONSTRAINT MT_FK_REPORTS_OWNER_ID FOREIGN KEY(OWNER_ID) REFERENCES MT_TB_USERS(ID);

CREATE TABLE IF NOT EXISTS MT_TB_REPORT_CHARTS (
    REPORT_ID BIGINT NOT NULL,
    NAME VARCHAR(100) NOT NULL
);
ALTER TABLE MT_TB_REPORT_CHARTS ADD CONSTRAINT MT_FK_REPORT_CHARTS_REPORT_ID FOREIGN KEY(REPORT_ID) REFERENCES MT_TB_REPORTS(ID);
